// Authored by Kimi Code (AI coding agent) — task CHRON-026.
//! Utility-AI scoring/selection baseline for CHRON-026 (the
//! `bench_utility_ai` scoring half, Master Spec §75): `select_action` over
//! precomputed candidate lists at 100 and 1,000 persons on one generated
//! 128×128 map with the deterministic `ActivitySites::place_defaults` site
//! set (six sites, two per kind — the lower end of the spec's 6–20 range).
//! Persons are plain `(LocalCoord, Needs)` pairs generated by a deterministic
//! stride pattern — `sim-ai` does not depend on `sim-core` — with both
//! drives strictly positive, so every person yields the full ten-candidate
//! set (3 Move + 2 Eat + 2 Sleep + 2 Work + 1 Idle). Each row times
//! `select_action` with `Weights::default()` and one perturbation spec
//! (`PerturbationRange::Zero`, plus `Bounded(25)` as the non-zero case).
//! Median of ten post-warm-up samples; correctness assertions remain
//! enabled. The enumeration/trace half is measured in CHRON-025's
//! `utility_ai_bench`. RSS is sampled best-effort via `ps` (KiB units on
//! macOS/Linux).

use std::hint::black_box;
use std::process::Command;
use std::time::Instant;

use palimpsest_sim_ai::{
    ActionCandidate, ActionKind, CandidateContext, NEED_MAX, NeedValue, Needs, PerturbationRange,
    PerturbationSpec, Selection, Weights, candidate_actions, select_action,
};
use palimpsest_sim_world::{
    ActivitySite, ActivitySites, LocalCoord, PathConfig, SiteKind, TerrainKind, WorldGenConfig,
    WorldMap, WorldSeed, find_path,
};

/// The two scales this baseline reports.
const SCALES: [usize; 2] = [100, 1_000];
/// Hunger pattern multiplier (deterministic, spreads raw values over the
/// full `NeedValue` range).
const HUNGER_STRIDE: i64 = 7_919;
/// Fatigue pattern multiplier (a different stride decorrelates the drives).
const FATIGUE_STRIDE: i64 = 10_873;
/// The full candidate count every person must yield: 3 Move + 2 per-site
/// candidates for each of Eat/Sleep/Work + the Idle baseline.
const CANDIDATES_PER_PERSON: usize = 10;
/// Seed for the non-zero perturbation row.
const PERTURBATION_SEED: u64 = 26_026;

fn main() {
    let mut arguments = std::env::args().skip(1);
    let sample_count = arguments.next().map_or(10, |value| {
        value.parse::<usize>().expect("sample count must be usize")
    });
    let warmup_count = arguments.next().map_or(2, |value| {
        value.parse::<usize>().expect("warmup count must be usize")
    });
    assert!(sample_count > 0, "sample count must be positive");

    let map = WorldMap::generate(WorldSeed::new(0), WorldGenConfig::default());
    let sites = ActivitySites::place_defaults(&map);
    assert_eq!(
        sites.len(),
        6,
        "place_defaults spreads six sites (two per kind) on generated terrain"
    );
    for kind in [SiteKind::Meal, SiteKind::Rest, SiteKind::Work] {
        assert_eq!(
            sites.sites_of(kind).count(),
            2,
            "place_defaults places two {kind:?} sites"
        );
    }

    let weights = Weights::default();
    let specs = [
        (0_i64, PerturbationSpec::ZERO),
        (
            25,
            PerturbationSpec::new(PERTURBATION_SEED, PerturbationRange::Bounded(25))
                .expect("epsilon in range"),
        ),
    ];

    for scale in SCALES {
        let persons = generate_persons(&map, &sites, scale);
        assert_eq!(persons.len(), scale);
        // Candidate lists are data construction (CHRON-025) and are
        // precomputed once; only scoring/selection is timed here.
        let mut prepared: Vec<(CandidateContext<'_>, Vec<ActionCandidate>)> =
            Vec::with_capacity(persons.len());
        for &(location, needs) in &persons {
            let context =
                CandidateContext::new(location, needs, &sites, &map, PathConfig::default());
            let candidates = candidate_actions(&context);
            assert_eq!(
                candidates.len(),
                CANDIDATES_PER_PERSON,
                "every person yields the full ten-candidate set"
            );
            prepared.push((context, candidates));
        }

        for (epsilon, spec) in specs {
            measure_row(
                &sites,
                &prepared,
                &weights,
                epsilon,
                &spec,
                sample_count,
                warmup_count,
            );
        }
    }
}

/// Times `select_action` over the prepared persons for one perturbation spec
/// and prints one JSON row: median of the post-warm-up samples, throughput,
/// RSS delta of retaining every selection, and the determinism checksum.
fn measure_row(
    sites: &ActivitySites,
    prepared: &[(CandidateContext<'_>, Vec<ActionCandidate>)],
    weights: &Weights,
    epsilon: i64,
    spec: &PerturbationSpec,
    sample_count: usize,
    warmup_count: usize,
) {
    let scale = prepared.len();
    let site_count = sites.len();
    for _ in 0..warmup_count {
        black_box(run_selections(prepared, weights, spec));
    }

    let mut samples = Vec::with_capacity(sample_count);
    let mut reference_checksum = None;
    for _ in 0..sample_count {
        let started = Instant::now();
        let (scored, checksum) = run_selections(prepared, weights, spec);
        samples.push(started.elapsed());
        assert_eq!(
            scored,
            scale * CANDIDATES_PER_PERSON,
            "every selection scores the full candidate set"
        );
        match reference_checksum {
            None => reference_checksum = Some(checksum),
            Some(reference) => assert_eq!(
                checksum, reference,
                "selection must be deterministic across samples"
            ),
        }
    }

    let rss_before = current_rss_bytes();
    let retained = retain_all_selections(prepared, weights, spec);
    black_box(&retained);
    let rss_after = current_rss_bytes();
    let rss_delta = rss_after
        .zip(rss_before)
        .map(|(after, before)| after.saturating_sub(before));

    samples.sort_unstable();
    let median = samples[sample_count / 2];
    let selections_f64 = f64::from(u32::try_from(scale).expect("scale fits u32"));
    let candidates_f64 =
        selections_f64 * f64::from(u32::try_from(CANDIDATES_PER_PERSON).expect("count fits u32"));
    println!(
        "{{\"persons\":{scale},\"sites\":{site_count},\
         \"perturbation_epsilon\":{epsilon},\"samples\":{sample_count},\
         \"candidates_per_selection\":{CANDIDATES_PER_PERSON},\
         \"selection_min_ns\":{},\"selection_median_ns\":{},\
         \"selection_max_ns\":{},\"selections_per_second\":{:.3},\
         \"candidates_scored_per_second\":{:.3},\"rss_delta_bytes\":{},\
         \"selection_checksum\":{}}}",
        samples.first().expect("samples exist").as_nanos(),
        median.as_nanos(),
        samples[sample_count - 1].as_nanos(),
        selections_f64 / median.as_secs_f64(),
        candidates_f64 / median.as_secs_f64(),
        json_u64(rss_delta),
        reference_checksum.expect("at least one sample ran"),
    );
}

/// Generates `count` deterministic persons: locations strided evenly over
/// the walkable cells that can reach every site (so each person sees the
/// full candidate set), hunger/fatigue patterned over the need range and
/// kept strictly positive so the Eat/Sleep gates stay open.
fn generate_persons(
    map: &WorldMap,
    sites: &ActivitySites,
    count: usize,
) -> Vec<(LocalCoord, Needs)> {
    let site_coords: Vec<LocalCoord> = [SiteKind::Meal, SiteKind::Rest, SiteKind::Work]
        .into_iter()
        .flat_map(|kind| sites.sites_of(kind).map(ActivitySite::coord))
        .collect();
    let connected: Vec<LocalCoord> = map
        .local()
        .coords()
        .filter(|coord| {
            map.local()
                .get(coord.x(), coord.y())
                .is_some_and(|kind| kind.is_walkable())
                && site_coords.iter().all(|target| {
                    find_path(
                        map.local(),
                        (coord.x(), coord.y()),
                        (target.x(), target.y()),
                        TerrainKind::is_walkable,
                        PathConfig::default(),
                    )
                    .is_ok()
                })
        })
        .collect();
    assert!(
        !connected.is_empty(),
        "some walkable cells must reach every site"
    );
    let stride = (connected.len() / count).max(1);
    (0..count)
        .map(|index| {
            let location = connected[(index * stride) % connected.len()];
            let patterned = i64::try_from(index).expect("person index fits i64");
            let hunger = NeedValue::from_raw((patterned * HUNGER_STRIDE) % NEED_MAX + 1)
                .expect("patterned hunger in range");
            let fatigue = NeedValue::from_raw((patterned * FATIGUE_STRIDE) % NEED_MAX + 1)
                .expect("patterned fatigue in range");
            (location, Needs::new(hunger, fatigue))
        })
        .collect()
}

/// Runs `select_action` for every prepared person; returns the total number
/// of scored candidates and a determinism checksum over the winners.
fn run_selections(
    prepared: &[(CandidateContext<'_>, Vec<ActionCandidate>)],
    weights: &Weights,
    spec: &PerturbationSpec,
) -> (usize, u64) {
    let mut scored = 0_usize;
    let mut checksum = 0_u64;
    for (context, candidates) in prepared {
        let selection = select_action(black_box(candidates), black_box(context), weights, spec)
            .expect("enumeration always yields the Idle baseline");
        // Correctness: one entry per candidate, the recorded outcome matches
        // the winner, and score == base + perturbation holds throughout.
        assert_eq!(selection.all_scores().len(), candidates.len());
        assert_eq!(
            selection.trace().selected(),
            Some(selection.candidate().order())
        );
        for entry in selection.all_scores() {
            assert_eq!(
                entry.score().get(),
                entry.base().get().saturating_add(entry.perturbation())
            );
        }
        let kind_key = match selection.candidate().kind() {
            ActionKind::Move => 0_u64,
            ActionKind::Eat => 1,
            ActionKind::Sleep => 2,
            ActionKind::Work => 3,
            ActionKind::Idle => 4,
        };
        checksum = checksum
            .wrapping_add(kind_key)
            .wrapping_add(selection.candidate().order())
            .wrapping_add(selection.score().get().cast_unsigned());
        scored += selection.all_scores().len();
    }
    (scored, checksum)
}

/// Runs and retains every selection for the RSS delta sample.
fn retain_all_selections(
    prepared: &[(CandidateContext<'_>, Vec<ActionCandidate>)],
    weights: &Weights,
    spec: &PerturbationSpec,
) -> Vec<Selection> {
    let mut retained = Vec::new();
    for (context, candidates) in prepared {
        retained.push(
            select_action(candidates, context, weights, spec)
                .expect("enumeration always yields the Idle baseline"),
        );
    }
    retained
}

fn current_rss_bytes() -> Option<u64> {
    let pid = std::process::id().to_string();
    let output = Command::new("ps")
        .args(["-o", "rss=", "-p", &pid])
        .output()
        .ok()?;
    let text = String::from_utf8(output.stdout).ok()?;
    text.trim().parse::<u64>().ok()?.checked_mul(1024)
}

fn json_u64(value: Option<u64>) -> String {
    value.map_or_else(|| "null".to_owned(), |number| number.to_string())
}
